### ISSUE TITLE
ouldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for FLAnimatedImage

### ISSUE THREAD

**Issue by Nomaq** [nihgwu/react-native-flanimatedimage#11]
When i try to submit the app i get the following error

Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for FLAnimatedImage

Apart from that is working fine i am using carthage

**Comment by nihgwu** [comment]
You mean you get this message when using CocoaPods?

**Comment by Nomaq** [comment]
Nevermind thank you very much i got the error from the script i included the DYSM in the run scripts by accident thank you
