### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000000000c

### ISSUE THREAD

**Issue by seigel** [nihgwu/react-native-flanimatedimage#15]
Wondering if anyone else is seeing crashes in deployed apps that come up as "__32-[RNFLAnimatedImage reloadImage]_block_invoke_2"

We seem to be getting a few and just wondering if there is any common knowledge that I might be missing?

Cheers

**Comment by nihgwu** [comment]
I know nothing about native iOS development actually, so need someone else to invest it
