### ISSUE TITLE
Local File?

### ISSUE THREAD

**Issue by DClark5218** [nihgwu/react-native-flanimatedimage#2]
Hey @nihgwu! I finally got this working in my project! I had a problem in the beginning loading #import "RCTImageUtils.h" into it, and with you being so kind to add this package I knew it was something enough tinkering could figure out!

I have run into a roadblock however. Whenever I try to load a local file with the require method it seems to get a weird error of trying to convert the src of the file to JSON.

```
<FLAnimatedImage 
    style={styles.slideImage}
    src={require('../img/test.gif')}
    resizeMode="contain"/>
```

Have you tried loading any files locally?

**Comment by nihgwu** [comment]
thanks for your report, I think I tried to load local GIFs, but I will try it again later,
`RCTImageUtils.h` is in the `react-native\Libraries\Image` package, to get the size of the image, includes the right path to the `Header Search Paths` would be OK

**Comment by DClark5218** [comment]
Got that part working! 👍

**Comment by nihgwu** [comment]
`src` should be a string, I get this value from `source`, but right now this component doesn't support local files, I will try to release a new version
Thank you, I missed this because I don't use local GIFs in my apps

**Comment by nihgwu** [comment]
@DClark5218 I've publish a new version to the npm

**Comment by DClark5218** [comment]
This works like charm :) Thank you!

**Comment by DClark5218** [comment]
@nihgwu - Actually may have to reopen this issue... for some reason the module stops working when you compile react in release.

Can you confirm?

**Comment by nihgwu** [comment]
I can confirm that

**Comment by nihgwu** [comment]
@DClark5218 have you test the latest version?

**Comment by DClark5218** [comment]
@nihgwu Yes. Works phenomenal! Thank you.
