### ISSUE TITLE
Xcode error when running app

### ISSUE THREAD

**Issue by fostertime** [nihgwu/react-native-flanimatedimage#3]
Hi there, I get the following Error after installing and running my app. 

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FLAnimatedImage", referenced from:
      objc-class-ref in libRNFLAnimatedImage.a(RNFLAnimatedImage.o)
  "_OBJC_CLASS_$_FLAnimatedImageView", referenced from:
      objc-class-ref in libRNFLAnimatedImage.a(RNFLAnimatedImage.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

any ideas?

**Comment by fostertime** [comment]
I resolved this... it was an issue with my Carthage install and setup. Sorry for the wasted issue! :)

**Comment by nihgwu** [comment]
you are welcome, hope this component would help you 😄

**Comment by neiker** [comment]
@fostertime can you add an explanation, please? I'm facing same problem


EDIT: It's important to pay attention to step 3, here https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

Its different from what I do when I linked others libs and that's why fail there.

**Comment by nihgwu** [comment]
@neiker Seems you have solved your problem already, you are right it's very important to follow the guide to add `FLAnimatedImage` via Carthage

**Comment by s349856186** [comment]
@nihgwu I pod install, get same error, how to do fix it ? Thanks
