### ISSUE TITLE
Gifs not running at full speed

### ISSUE THREAD

**Issue by alexwasner** [nihgwu/react-native-flanimatedimage#4]
First off,
This fixed my crash bug with loading large gifs all at the start of my app, so thanks for making this. It seems my animations are running at a lower frame rate than what they are when viewed on a computer or when they are just in an `<Image/>` tag. Is there a way to tweak the playback speed?

**Comment by nihgwu** [comment]
Thanks for report, I'll take a look at it

**Comment by kiki-le-singe** [comment]
Hi,

Any news about this issue?

I have this problem too. When I use the `<Image />` component, my view appears slower but animated Gifs are faster. But when I use the `<FLAnimatedImage />` component my view appears faster but animated Gifs are slower.

Thanks

**Comment by nihgwu** [comment]
perhaps it's a issue from FlanimatedImage, https://github.com/Flipboard/FLAnimatedImage/issues/161

**Comment by kiki-le-singe** [comment]
After reading this issue: [Flipboard/FLAnimatedImage#161](https://github.com/Flipboard/FLAnimatedImage/issues/161), I think it's because I usually tried `<FLAnimatedImage />` on simulator. When I executed it on real device, it seems to work fine

**Comment by icyKira** [comment]
Tried this on a real device and still its not running at full speed. Tried with two different gifs
