### ISSUE TITLE
Prevent GIF Looping

### ISSUE THREAD

**Issue by kiki-le-singe** [nihgwu/react-native-flanimatedimage#8]
Hi,

Is it possible to prevent looping?

When I open my animated gifs in the browser (Chrome, Safari), it doesn't loop. But on ios (simulator included) and android devices my gifs are playing forever.

Thanks

**Comment by nihgwu** [comment]
Seems it's a issue of FlanimatedImage itself, see #https://github.com/Flipboard/FLAnimatedImage/issues/156 and there is a pending PR https://github.com/Flipboard/FLAnimatedImage/pull/169

**Comment by kiki-le-singe** [comment]
Ok interesting!

Have you ever had this problem?

Thanks for your return.

**Comment by nihgwu** [comment]
I think there should be, but actually I don't quite concern about that, I just want to stop OOM crashes from gif issue

**Comment by kiki-le-singe** [comment]
Yes I understand and what you did works very well!

Thanks
